SELECT 
    (SELECT MAX(ID) + 1) AS ID, 
    ID AS VIAGEM, 
    USUARIO AS TECNICO, 
    1 AS ATRIBUITO, 
    DATA_INICIO, 
    DATA_FIM, 
    N_DIARIA, 
    V_DIARIA,
    N_INTRANET,
    DATA
FROM REGISTRO_VIAGENS    